name: Fork and Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"

jobs:
  ForkSync:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps:
    - name: Checkout target repository
      uses: actions/checkout@v4.1.7

    - name: "Setup sing-box"
      env:
        SING_BOX_DEB_URL: "https://github.com/SagerNet/sing-box/releases/download/v1.10.0-alpha.28/sing-box_1.10.0-alpha.28_linux_amd64.deb"
      run: |
        set -Eeuo pipefail
        wget -O sing-box.deb $SING_BOX_DEB_URL
        sudo dpkg -i sing-box.deb

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - uses: actions/setup-node@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests pyyaml

    - name: Download content
      run: |
        URL="https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/adservers.txt"
        OUTPUT_FILE="./rule/adservers.txt"

        curl -L $URL -o $OUTPUT_FILE

        if [ -f "$OUTPUT_FILE" ]; then
          echo "Download successful: $OUTPUT_FILE"
        else
          echo "Download failed."
          exit 1
        fi

    - name: Convert AdGuard DNS Filter to sing-box rule set
      run: |
        sing-box rule-set convert --type adguard --output ./rule/adservers.srs ./rule/adservers.txt

    - name: Run script
      run: python ../main.py
      working-directory: ./rule/

    - name: Commit and push config.json
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add ./rule/*.json
        git add ./rule/*.srs
        git add ./rule/*.txt

        # 检查是否有文件被修改
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        else
          git commit -m "Update rules"
          git push
        fi

    - name: Add and Commit
      run: |
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git pull --rebase origin X
          git push origin X
        else
          echo "No changes to commit."
        fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
